// <auto-generated />
using System;
using DeliveryControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryControl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128093059_AddFgMappingTable")]
    partial class AddFgMappingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DeliveryControl.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewData")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldData")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("Module");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Module", "Action");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("DeliveryControl.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cycle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Docking")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ETD")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pickup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedDate = new DateTime(2026, 1, 28, 16, 30, 58, 775, DateTimeKind.Local).AddTicks(4569),
                            CustomerCode = "CUST001",
                            CustomerName = "PT ABC Manufacturing",
                            IsActive = true,
                            Route = "Route A",
                            SKID = "10 SKID"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedDate = new DateTime(2026, 1, 28, 16, 30, 58, 775, DateTimeKind.Local).AddTicks(4572),
                            CustomerCode = "CUST002",
                            CustomerName = "PT XYZ Industries",
                            IsActive = true,
                            Route = "Route B",
                            SKID = "15 SKID"
                        });
                });

            modelBuilder.Entity("DeliveryControl.Models.DeliveryItem", b =>
                {
                    b.Property<int>("DeliveryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DeliveryItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ScheduleId", "ItemId");

                    b.ToTable("DeliveryItems");
                });

            modelBuilder.Entity("DeliveryControl.Models.DeliverySchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualEnterDockTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualPickupTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cycle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ETD")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnterDockTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparationStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalActualQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTargetQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ScheduleNumber")
                        .IsUnique();

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "ScheduledDate");

                    b.ToTable("DeliverySchedules");
                });

            modelBuilder.Entity("DeliveryControl.Models.FgMapping", b =>
                {
                    b.Property<int>("FgMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoRack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("QtyLot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("FgMappingId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("FgMappings");
                });

            modelBuilder.Entity("DeliveryControl.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Category = "Raw Material",
                            CreatedDate = new DateTime(2026, 1, 28, 16, 30, 58, 775, DateTimeKind.Local).AddTicks(4679),
                            Description = "Raw material untuk produksi",
                            IsActive = true,
                            ItemCode = "ITM001",
                            ItemName = "Raw Material A",
                            MaxStock = 20,
                            MinStock = 5,
                            Unit = "KG",
                            Weight = 1.0m
                        },
                        new
                        {
                            ItemId = 2,
                            Category = "Finished Goods",
                            CreatedDate = new DateTime(2026, 1, 28, 16, 30, 58, 775, DateTimeKind.Local).AddTicks(4682),
                            Description = "Produk jadi siap kirim",
                            IsActive = true,
                            ItemCode = "ITM002",
                            ItemName = "Finished Product B",
                            MaxStock = 20,
                            MinStock = 5,
                            Unit = "PCS",
                            Weight = 2.5m
                        },
                        new
                        {
                            ItemId = 3,
                            Category = "Packaging",
                            CreatedDate = new DateTime(2026, 1, 28, 16, 30, 58, 775, DateTimeKind.Local).AddTicks(4684),
                            Description = "Material packaging",
                            IsActive = true,
                            ItemCode = "ITM003",
                            ItemName = "Packaging Material",
                            MaxStock = 20,
                            MinStock = 5,
                            Unit = "BOX",
                            Weight = 0.5m
                        });
                });

            modelBuilder.Entity("DeliveryControl.Models.PoolingRecord", b =>
                {
                    b.Property<int>("PoolingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PoolingId");

                    b.HasIndex("ItemId");

                    b.ToTable("PoolingRecords");
                });

            modelBuilder.Entity("DeliveryControl.Models.PreparationRecord", b =>
                {
                    b.Property<int>("PreparationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kanban")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PreparationId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("PreparationRecords");
                });

            modelBuilder.Entity("DeliveryControl.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("DeliveryControl.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeliveryControl.Models.DeliveryItem", b =>
                {
                    b.HasOne("DeliveryControl.Models.Item", "Item")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryControl.Models.DeliverySchedule", "DeliverySchedule")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliverySchedule");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DeliveryControl.Models.DeliverySchedule", b =>
                {
                    b.HasOne("DeliveryControl.Models.Customer", "Customer")
                        .WithMany("DeliverySchedules")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DeliveryControl.Models.FgMapping", b =>
                {
                    b.HasOne("DeliveryControl.Models.Item", "Item")
                        .WithOne()
                        .HasForeignKey("DeliveryControl.Models.FgMapping", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DeliveryControl.Models.PoolingRecord", b =>
                {
                    b.HasOne("DeliveryControl.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DeliveryControl.Models.PreparationRecord", b =>
                {
                    b.HasOne("DeliveryControl.Models.DeliverySchedule", "DeliverySchedule")
                        .WithMany("PreparationRecords")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DeliverySchedule");
                });

            modelBuilder.Entity("DeliveryControl.Models.Customer", b =>
                {
                    b.Navigation("DeliverySchedules");
                });

            modelBuilder.Entity("DeliveryControl.Models.DeliverySchedule", b =>
                {
                    b.Navigation("DeliveryItems");

                    b.Navigation("PreparationRecords");
                });

            modelBuilder.Entity("DeliveryControl.Models.Item", b =>
                {
                    b.Navigation("DeliveryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
